In [ ]:
'''
@Author: Ayur Ninawe
@Date: 2021-07-10 18:00:30
@Last Modified by: Ayur Ninawe
@Last Modified time: 2021-07-10 18:00:30
@Title : Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
'''

In [1]:
import numpy as np
from loggerfile import Log 

In [2]:
def checkerboard():
    try:
        array=np.zeros((8,8))
        array[1::2,::2]=1
        array[::2,1::2]=1

        print(array.reshape(8,8))
    
    except Exception as e:
        loggerfile.Log.logging.error(e)

In [3]:
checkerboard()

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
