In [ ]:
'''
@Author: Ayur Ninawe
@Date: 2021-07-11 18:00:30
@Last Modified by: Ayur Ninawe
@Last Modified time: 2021-07-11 18:00:30
@Title : Write a Python program to convert a list and tuple into arrays.
'''

In [1]:
import numpy as np
from loggerfile import Log

In [2]:
def convertToArray():
    """
        Description:
     Function to convert a list and tuple into arrays.
     """
    try:
        list=[1,2,3,4,5,6,7,8]
        tuple=((8,4,6),(1,2,3))
        print(np.array(list))
        print(np.array(tuple))
    except Exception as e:
        loggerfile.Log.logging.error(e)

In [3]:
convertToArray()

[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]
