In [ ]:
'''
@Author: Ayur Ninawe
@Date: 2021-07-10 18:00:30
@Last Modified by: Ayur Ninawe
@Last Modified time: 2021-07-10 18:00:30
@Title : Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]
'''

In [2]:
import numpy as np
from loggerfile import Log

In [3]:
def createMatrix():
    try:
        array=np.arange(2,11)
        print(array.reshape(3,3))
    except Exception as e:
        loggerfile.Log.logging.error(e)

In [4]:
createMatrix()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
