In [ ]:
'''
@Author: Ayur Ninawe
@Date: 2021-07-12 18:00:30
@Last Modified by: Ayur Ninawe
@Last Modified time: 2021-07-12 18:00:30
@Title : Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
'''

In [1]:
import numpy as np 
from loggerfile import Log

In [2]:
def scalar():
    """
    Description : 
        function to create an array of (3, 4) shape, multiply every element
        value by 3 and display the new array.
    """
    try:
        array=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
        print(array*3)
    except Exception as e:
        loggerfile.Log.logging.error(e)   

In [3]:
scalar()

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
