In [ ]:
'''
@Author: Ayur Ninawe
@Date: 2021-07-12 18:00:30
@Last Modified by: Ayur Ninawe
@Last Modified time: 2021-07-12 18:00:30
@Title : Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]
'''

In [1]:
import numpy as np 
from loggerfile import Log

In [4]:
def zeroones():
    """
    Description : 
        function to create an array with zeros and ones.
    """
    try:
        array=np.zeros((4,3))
        for i in range(0,3):
            array[i+1:,:i+1]=1
        print(array)
    except Exception as e:
        loggerfile.Log.logging.error(e) 

In [5]:
zeroones()

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
